//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diversia.Backend.BlogSVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlogSVC.IBlog")]
    public interface IBlog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlog/Paginated", ReplyAction="http://tempuri.org/IBlog/PaginatedResponse")]
        Diversia.Core.Pager.Page<Diversia.Models.BlogPost.BlogPostModel> Paginated(Diversia.Core.Pager.FindRequestImpl<Diversia.Core.Filter.SearchFilter> filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlog/Paginated", ReplyAction="http://tempuri.org/IBlog/PaginatedResponse")]
        System.Threading.Tasks.Task<Diversia.Core.Pager.Page<Diversia.Models.BlogPost.BlogPostModel>> PaginatedAsync(Diversia.Core.Pager.FindRequestImpl<Diversia.Core.Filter.SearchFilter> filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogChannel : Diversia.Backend.BlogSVC.IBlog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogClient : System.ServiceModel.ClientBase<Diversia.Backend.BlogSVC.IBlog>, Diversia.Backend.BlogSVC.IBlog {
        
        public BlogClient() {
        }
        
        public BlogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Diversia.Core.Pager.Page<Diversia.Models.BlogPost.BlogPostModel> Paginated(Diversia.Core.Pager.FindRequestImpl<Diversia.Core.Filter.SearchFilter> filter) {
            return base.Channel.Paginated(filter);
        }
        
        public System.Threading.Tasks.Task<Diversia.Core.Pager.Page<Diversia.Models.BlogPost.BlogPostModel>> PaginatedAsync(Diversia.Core.Pager.FindRequestImpl<Diversia.Core.Filter.SearchFilter> filter) {
            return base.Channel.PaginatedAsync(filter);
        }
    }
}
